Made parallel test as default
browserstack/jbehave-browserstack pull request #21
Opened 2023-03-24 11:29 UTC by agarneha1331

2023-03-27 07:23 UTC, kamal-kaur04 requested changes

2023-03-27 07:23 UTC, kamal-kaur04 commented on pom.xml
> +            <activation>
Can remove this and add suite xml file at root level.

2023-03-28 06:54 UTC, kamal-kaur04 approved these changes

2023-03-29 17:39 UTC, francisf approved these changes

2023-03-29 17:39 UTC, merged